# Generated by Django 4.0.5 on 2022-12-27 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='select',
            field=models.BooleanField(db_index=True, default=True, verbose_name='избранная'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
